/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'qos' at '12/2/15 6:08 PM' with Gradle 2.9
 *
 * @author qos, @date 12/2/15 6:08 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
